apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primomcp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0,::/0"
spec:
  ingressClassName: nginx
  rules:
    - host: primomcp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: primomcp
                port:
                  number: 80
